### ISSUE TITLE
panic at program termination

### ISSUE THREAD

**Issue by Andreone** [influxdata/influx-stress#32]
Tested on Ubtuntu 16.04 and Windows 10 Pro, same behavior:

```
Using point template: ctr,some=tag n=0i <timestamp>
Using batch size of 10000 line(s)
Spreading writes across 100000 series
Output is unthrottled
Using 20 concurrent writer(s)
Running until ~18446744073709551615 points sent or until ~1m0s has elapsed
panic: send on closed channel

goroutine 49 [running]:
github.com/influxdata/influx-stress/cmd.(*multiSink).run(0xc04207c5a0)
        C:/Users/Andreone/go/src/github.com/influxdata/influx-stress/cmd/insert.go:306 +0x109
created by github.com/influxdata/influx-stress/cmd.(*multiSink).Open
        C:/Users/Andreone/go/src/github.com/influxdata/influx-stress/cmd/insert.go:298 +0x9b
```

**Comment by foobar** [comment]
i'm seeing the same issue on CentOS7

**Comment by CoderSong2015** [comment]
same

**Comment by chengshiwen** [comment]
This problem has been fixed by [chengshiwen/influx-stress](https://github.com/chengshiwen/influx-stress)
