### ISSUE TITLE
超过500万条数据的插入会报错

### ISSUE THREAD

**Issue by 9renfei9** [influxdata/influx-stress#36]
[2019-06-30 22:15:09] Error sending write: dialing to the given TCP address timed out
[2019-06-30 22:15:09] Error sending write: dialing to the given TCP address timed out
[2019-06-30 22:15:09] Error sending write: dialing to the given TCP address timed out
[2019-06-30 22:15:09] Error sending write: dialing to the given TCP address timed out
[2019-06-30 22:15:09] Error sending write: dialing to the given TCP address timed out
[2019-06-30 22:15:09] Error sending write: dialing to the given TCP address timed out
[2019-06-30 22:15:09] Error sending write: dialing to the given TCP address timed out
[2019-06-30 22:15:09] Error sending write: dialing to the given TCP address timed out
[2019-06-30 22:15:09] Error sending write: dialing to the given TCP address timed out
[2019-06-30 22:15:09] Error sending write: dialing to the given TCP address timed out
panic: send on closed channel

goroutine 52 [running]:
github.com/influxdata/influx-stress/cmd.(*multiSink).run(0xc4200925d0)
	/root/go/src/github.com/influxdata/influx-stress/cmd/insert.go:306 +0x102
created by github.com/influxdata/influx-stress/cmd.(*multiSink).Open
	/root/go/src/github.com/influxdata/influx-stress/cmd/insert.go:298 +0x94

**Comment by chengshiwen** [comment]
@9renfei9 
同[#32 ](https://github.com/influxdata/influx-stress/issues/32)
已经在 [chengshiwen/influx-stress](https://github.com/chengshiwen/influx-stress) 修复
